import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";
import { Toaster } from "react-hot-toast";

const inter = Manrope({ subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={[inter.className, "flex h-screen w-screen bg-white max-h-screen"].join(
          " "
        )}
      >
        {children}
        <Toaster position="bottom-right" toastOptions={{ duration: 5000 }} />
      </body>
    </html>
  );
}
