import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";
import { HomeSidebar } from "@/src/components/layout";

const inter = Manrope({ subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={[inter.className, "flex h-screen w-screen bg-white"].join(" ")}>
        <div className="flex flex-col gap-3 border border-red-600 bg-[#F0F4FA] p-6">
          <HomeSidebar />
        </div>
        <div className="w-full">{children}</div>
      </body>
    </html>
  );
}
