import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import type { ReactNode } from "react";
import { Toaster } from "react-hot-toast";
import { locales } from "@/i18n";
import { getMessages, unstable_setRequestLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

const inter = Manrope({ subsets: ["latin", "cyrillic"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export async function generateStaticParams() {
  return locales.map((locale) => {
    locale;
  });
}

export default async function RootLayout({
  children,
  params: { locale }
}: Readonly<{
  children: ReactNode;
  params: { locale: string };
}>) {
  unstable_setRequestLocale(locale);
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <NextIntlClientProvider messages={messages}>
        <body
          className={[
            inter.className,
            "flex h-screen w-screen bg-white max-h-screen"
          ].join(" ")}
        >
          {children}
          <Toaster position="bottom-right" toastOptions={{ duration: 5000 }} />
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
